### ISSUE TITLE
Option to throw SIGABRT on finding a Type Confusion

### ISSUE THREAD

**Issue by Ayrx** [HexHive/HexType#4]
Is it possible to add an option, possibly hidden behind an `#ifdef`, where the sanitizer throws a `SIGABRT` when it discovers a type confusion? This should make it play nice with fuzzers like `afl-fuzz`.

I managed to patch `void printTypeConfusion` at `src/compiler-rt-files/hextype_report.cc` to do this but there probably is a better place to call the `abort()`.

**Comment by jys0710** [comment]
Thanks for your comment. I updated this option as below commit (please check this :)). 
- https://github.com/HexHive/HexType/commit/369d218853755d809e72afb1bb1ee1c68656fd25

**Comment by Ayrx** [comment]
That looks good! Thanks. :)
